[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM20
monitor_port = COM20
upload_speed = 115200
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBRIDGE_WIFI_STA_SSID=\"NachoWi-Fi\"
  -DBRIDGE_WIFI_STA_PASS=\"NrMaintain1!\"
  -DBRIDGE_WIFI_STA_TIMEOUT_MS=15000
